import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner/Banner";
import Card from "../components/Card/CardComponent";
import React, { useEffect, useState } from "react";
import { fetchAllCoffeeStore } from "../lib/coffeeStoreLibrary";
import useTrackLocation from "../hooks/useTrackLocation";
import { useDispatch, useSelector } from "react-redux";
import { setCoffeeStore } from "../store/action/action";

export async function getStaticProps(context) {
  const fetchCoffeeStore = await fetchAllCoffeeStore();
  return {
    props: { coffeeStores: fetchCoffeeStore, message: "hello" }, // will be passed to the page component as props
  };
}
const Home = (props) => {
  const { handleTrackLocation, locationErrorMsg, isFindingLocation } =
    useTrackLocation();

  const { latLong, coffeeStore } = useSelector((state) => state.reducer);
  const [coffeeStoreError, setCoffeeStoreError] = useState(null);
  const dispatch = useDispatch();
  const locationHandler = async () => {
    try {
      const response = await fetch(
        `/api/getCoffeeStoreByLocation?latLong=${latLong}&limit=30`
      );
      const coffeeStoresData = await response.json();
      // setCoffeeStores(fetchCoffeeStore);
      dispatch(setCoffeeStore(coffeeStoresData));
      setCoffeeStoreError("");
    } catch (error) {
      setCoffeeStoreError(error.message);
    }
  };
  useEffect(() => {
    if (latLong) {
      locationHandler();
    }
  }, [latLong]);
  const handleOnBannerBtnClick = () => {
    handleTrackLocation();
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Conoisseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/*<h1 className={styles.title}>Coffee Connoissuer</h1>*/}
        <Banner
          buttonText={isFindingLocation ? "Locating..." : "View stores nearby"}
          handleOnClick={handleOnBannerBtnClick}
        />
        {locationErrorMsg && <p>Something went wrong:{locationErrorMsg}</p>}
        {coffeeStoreError && <p>Something went wrong:{coffeeStoreError}</p>}
        <div className={styles.heroImage}>
          <Image
            src="/static/hero-image.png"
            width={700}
            height={400}
            alt="hero-image"
          />
        </div>
        {coffeeStore.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Stores Near Me</h2>
            <div className={styles.cardLayout}>
              {coffeeStore?.map((element, index) => {
                return (
                  <Card
                    key={index}
                    name={element.name}
                    imgUrl={
                      element.imgUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                    href={`/coffee-store/${element.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </div>
        )}

        {props.coffeeStores.length > 0 && (
          <div className={styles.sectionWrapper}>
            <h2 className={styles.heading2}>Toronto Stores</h2>
            <div className={styles.cardLayout}>
              {props.coffeeStores?.map((element, index) => {
                return (
                  <Card
                    key={index}
                    name={element.name}
                    imgUrl={
                      element.imgUrl ||
                      "https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80"
                    }
                    href={`/coffee-store/${element.fsq_id}`}
                    className={styles.card}
                  />
                );
              })}
            </div>
          </div>
        )}
      </main>
    </div>
  );
};
export default Home;
